namespace Mockable.Core.Exceptions;

/// <summary>
/// Represents an exception generated by Mockable.
/// </summary>
public class MockableException : Exception
{
    /// <summary>
    /// Creates a MockableException instance.
    /// </summary>
    public MockableException()
    {
    }

    /// <summary>
    /// Creates a MockableException instance with a specified error message.
    /// </summary>
    /// <param name="message">The message that describes the error.</param>
    public MockableException(string? message)
        :base(message)
    {
    }

    /// <summary>
    /// Creates a MockableException instance with a specified error message
    /// and a reference to the inner exception that is the cause of the
    /// exception.
    /// </summary>
    /// <param name="message">The message that describes the error</param>
    /// <param name="innerException">
    /// The exception that is the cause of the current exception, or a null
    /// reference if no inner exception is specified.
    /// </param>
    public MockableException(string? message, Exception? innerException)
        :base(message, innerException)
    {
    }
}
